extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:react/recommended'
env:
  browser: true
  es6: true
settings:
  react:
    version: detect
plugins:
  - prettier
  - '@typescript-eslint'
  - react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  jsx: true
  sourceType: module
  arrowFunctions: true
rules:
  array-callback-return: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  react/react-in-jsx-scope: off
